(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOneWIP",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[
                {
                 "height":64,
                 "id":1346,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":1,
                 "id":1348,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1,
                 "x":57,
                 "y":247
                }, 
                {
                 "height":32,
                 "id":1349,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":0,
                 "y":576
                }],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":7,
                 "height":90,
                 "id":1361,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rhombusBoulder",
                 "visible":true,
                 "width":90,
                 "x":2970.15151515152,
                 "y":108.636363636364
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1362,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":3015,
                 "y":126
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1363,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":2239,
                 "y":389
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1364,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":1938,
                 "y":146
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1365,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":1395,
                 "y":483
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":1366,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock01",
                 "visible":true,
                 "width":74,
                 "x":2879,
                 "y":595
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1367,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":2922,
                 "y":609
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1368,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":2883,
                 "y":621
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1369,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":2920,
                 "y":539
                }, 
                {
                 "gid":16,
                 "height":30,
                 "id":1373,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"bubble",
                 "visible":true,
                 "width":30,
                 "x":3037,
                 "y":145
                }, 
                {
                 "gid":16,
                 "height":30,
                 "id":1374,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"bubble",
                 "visible":true,
                 "width":30,
                 "x":3060,
                 "y":171
                }, 
                {
                 "gid":16,
                 "height":30,
                 "id":1375,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"bubble",
                 "visible":true,
                 "width":30,
                 "x":3084,
                 "y":198
                }, 
                {
                 "gid":15,
                 "height":27,
                 "id":1378,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"capsule1",
                 "visible":true,
                 "width":33,
                 "x":3132,
                 "y":117
                }, 
                {
                 "gid":5,
                 "height":27,
                 "id":1379,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock04",
                 "visible":true,
                 "width":27,
                 "x":3120,
                 "y":177
                }, 
                {
                 "gid":5,
                 "height":27,
                 "id":1380,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock04",
                 "visible":true,
                 "width":27,
                 "x":3179,
                 "y":195
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1381,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":3142,
                 "y":183
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1382,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":3143,
                 "y":215
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":1383,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock01",
                 "visible":true,
                 "width":74,
                 "x":3191,
                 "y":200
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1384,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":3244,
                 "y":153
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1385,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":3272,
                 "y":137
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1386,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":2949,
                 "y":85
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1387,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":3337,
                 "y":85
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":1388,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock01",
                 "visible":true,
                 "width":74,
                 "x":3291,
                 "y":75
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":1389,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock01",
                 "visible":true,
                 "width":74,
                 "x":3012,
                 "y":57
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":1390,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock01",
                 "visible":true,
                 "width":74,
                 "x":3339,
                 "y":53
                }, 
                {
                 "gid":3,
                 "height":40,
                 "id":1391,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock02",
                 "visible":true,
                 "width":40,
                 "x":3379,
                 "y":71
                }, 
                {
                 "gid":4,
                 "height":37,
                 "id":1392,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"rock03",
                 "visible":true,
                 "width":32,
                 "x":3367,
                 "y":91
                }, 
                {
                 "gid":15,
                 "height":27,
                 "id":1393,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"capsule1",
                 "visible":true,
                 "width":33,
                 "x":3198,
                 "y":98
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":9,
                 "height":21,
                 "id":1252,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":191,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1306,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":239,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1307,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":287,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1308,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":335,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1309,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":383,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1310,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":431,
                 "y":95
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1311,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":623,
                 "y":151
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1312,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":687,
                 "y":151
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1313,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":751,
                 "y":151
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1314,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":815,
                 "y":151
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1315,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":879,
                 "y":151
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1317,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1056,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1318,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1096,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1319,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1136,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1320,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1176,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1321,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1216,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1322,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"3"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1256,
                 "y":376
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1327,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"4"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1428,
                 "y":574
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1328,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"4"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1556,
                 "y":422
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1329,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"4"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1700,
                 "y":270
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1330,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"4"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1844,
                 "y":118
                }, 
                {
                 "gid":32,
                 "height":34,
                 "id":1350,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":50
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"loop"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-200
                        }],
                 "rotation":0,
                 "type":"miniBoss1",
                 "visible":true,
                 "width":60,
                 "x":11696,
                 "y":327
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1351,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2072.87878787879,
                 "y":131.212121212121
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1352,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2188.0303030303,
                 "y":222.121212121212
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1354,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2191.06060606061,
                 "y":316.060606060606
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1355,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2369.84848484848,
                 "y":476.666666666667
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1356,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2518.33333333333,
                 "y":376.666666666667
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1357,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":2220.45454545455,
                 "y":170.454545454545
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1358,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":2350.75757575758,
                 "y":291.666666666667
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1359,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":2575,
                 "y":558.333333333333
                }, 
                {
                 "gid":20,
                 "height":30,
                 "id":1371,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":0.785398163
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2905,
                 "y":520
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":9,
         "name":"Foreground",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":14,
 "nextobjectid":1394,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/mapAssets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":700
});