(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOne",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":7,
                 "height":90,
                 "id":765,
                 "name":"",
                 "rotation":0,
                 "type":"rhombusBoulder",
                 "visible":true,
                 "width":90,
                 "x":11.6363636363636,
                 "y":555.212121212121
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":9,
                 "height":21,
                 "id":734,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":0,
                 "y":64
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":735,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":32,
                 "y":64
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":736,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":64,
                 "y":64
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":737,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":96,
                 "y":64
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":738,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":192,
                 "y":192
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":739,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":256,
                 "y":192
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":740,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":320,
                 "y":192
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":745,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":384,
                 "y":352
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":746,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":416,
                 "y":352
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":747,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":448,
                 "y":352
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":748,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":512,
                 "y":352
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":749,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":352
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":755,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":128,
                 "y":128
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":760,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":832,
                 "y":576
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":761,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":928,
                 "y":576
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":762,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1024,
                 "y":576
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":763,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":864,
                 "y":576
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":764,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":960,
                 "y":576
                }, 
                {
                 "gid":22,
                 "height":30,
                 "id":792,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1SE",
                 "visible":true,
                 "width":30,
                 "x":228,
                 "y":418
                }, 
                {
                 "gid":21,
                 "height":30,
                 "id":793,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1S",
                 "visible":true,
                 "width":30,
                 "x":157,
                 "y":475
                }, 
                {
                 "gid":23,
                 "height":30,
                 "id":794,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1SW",
                 "visible":true,
                 "width":30,
                 "x":94,
                 "y":416
                }, 
                {
                 "gid":24,
                 "height":30,
                 "id":795,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1W",
                 "visible":true,
                 "width":30,
                 "x":34,
                 "y":348
                }, 
                {
                 "gid":20,
                 "height":30,
                 "id":796,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1NW",
                 "visible":true,
                 "width":30,
                 "x":94,
                 "y":293
                }, 
                {
                 "gid":20,
                 "height":30,
                 "id":797,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1NW",
                 "visible":true,
                 "width":30,
                 "x":94,
                 "y":293
                }, 
                {
                 "gid":18,
                 "height":30,
                 "id":798,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1E",
                 "visible":true,
                 "width":30,
                 "x":162,
                 "y":322
                }, 
                {
                 "gid":19,
                 "height":30,
                 "id":799,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1NE",
                 "visible":true,
                 "width":30,
                 "x":195,
                 "y":349
                }, 
                {
                 "gid":21,
                 "height":30,
                 "id":800,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1S",
                 "visible":true,
                 "width":30,
                 "x":159,
                 "y":381
                }, 
                {
                 "gid":24,
                 "height":30,
                 "id":801,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1W",
                 "visible":true,
                 "width":30,
                 "x":125,
                 "y":351
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":8,
 "nextobjectid":802,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":400
});