(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelThreeWIP",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[
                {
                 "height":64,
                 "id":1252,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":-0.166667
                }, 
                {
                 "height":32,
                 "id":1253,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":575.833
                }, 
                {
                 "height":64,
                 "id":1254,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":-0.166667
                }, 
                {
                 "height":32,
                 "id":1255,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":575.833
                }],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":66,
                 "height":150,
                 "id":1328,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-869.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1329,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-720.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1330,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-570.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1331,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-420.416666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1332,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-270.916666666667,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1333,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-121.416666666667,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1334,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":28.5833333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1335,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":178.583333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1336,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":329.083333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1337,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-869.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1338,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-719.416666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1339,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-569.416666666667,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1340,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-418.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1341,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-268.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1342,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-118.916666666667,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1343,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":31.5833333333333,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1344,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":181.083333333333,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1345,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":330.583333333333,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1350,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":481.081833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1351,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":631.584833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1352,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":781.584833333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1353,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":932.084833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1354,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1082.08483333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1355,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1232.08483333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1356,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1382.58483333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1357,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1532.08513333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1358,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1681.58483333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1359,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":478.706833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1360,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":627.709833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1361,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":777.709833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1362,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":928.209833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1363,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1077.70983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1364,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1227.20983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1365,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1377.20983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1366,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1527.21013333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1367,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1677.70983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":74,
                 "height":74,
                 "id":1372,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":80,
                 "x":1852.66666666667,
                 "y":483.333333333333
                }, 
                {
                 "gid":74,
                 "height":74,
                 "id":1373,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":80,
                 "x":1977.33333333333,
                 "y":483.333333333333
                }, 
                {
                 "gid":74,
                 "height":74,
                 "id":1374,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":80,
                 "x":1918.66666666667,
                 "y":409.333333333333
                }, 
                {
                 "gid":71,
                 "height":90,
                 "id":1375,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Cast",
                 "visible":true,
                 "width":76,
                 "x":2087.33333333333,
                 "y":481.333333333333
                }, 
                {
                 "gid":71,
                 "height":90,
                 "id":1376,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Cast",
                 "visible":true,
                 "width":76,
                 "x":2085.66666666667,
                 "y":153.666666666667
                }, 
                {
                 "gid":72,
                 "height":74,
                 "id":1377,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Plus",
                 "visible":true,
                 "width":76,
                 "x":2422.66666666667,
                 "y":481.333333333333
                }, 
                {
                 "gid":72,
                 "height":74,
                 "id":1378,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Plus",
                 "visible":true,
                 "width":76,
                 "x":2424,
                 "y":407.333333333333
                }, 
                {
                 "gid":73,
                 "height":76,
                 "id":1394,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square",
                 "visible":true,
                 "width":76,
                 "x":2613.33333333333,
                 "y":482.333333333333
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1396,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1827.58528787879,
                 "y":632.674225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1397,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1976.58528787879,
                 "y":632.674225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1398,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2126.58528787879,
                 "y":632.674225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1399,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2277.08528787879,
                 "y":632.674225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1400,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2426.58528787879,
                 "y":633.174225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1401,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2576.08528787879,
                 "y":633.174225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1402,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2726.08558787879,
                 "y":633.174225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1403,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2876.08528787879,
                 "y":633.174225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1404,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3026.58528787879,
                 "y":633.174225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1405,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1831.58528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1406,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1981.08528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1407,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2131.08528787879,
                 "y":66.1742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1408,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2281.58528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1409,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2431.58528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1410,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2581.58528787879,
                 "y":66.1742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1411,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2732.08558787879,
                 "y":66.1742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1412,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":2881.58528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1413,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3031.08528787879,
                 "y":65.6742257575758
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1414,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3181.58428787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1415,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3332.08728787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1416,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3482.08728787879,
                 "y":65.8409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1417,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3632.58728787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1418,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3782.58228787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1419,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3932.58228787879,
                 "y":65.8409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1420,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4083.08228787879,
                 "y":65.8409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1421,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4232.59228787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1422,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4382.08228787879,
                 "y":65.3409257575757
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1423,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3176.20928787879,
                 "y":632.549225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1424,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3325.21228787879,
                 "y":632.549225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1425,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3475.21228787879,
                 "y":632.549225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1426,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3625.71228787879,
                 "y":632.549225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1427,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3775.21228787879,
                 "y":633.049225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1428,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":3924.71228787879,
                 "y":633.049225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1429,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4074.71228787879,
                 "y":633.049225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1430,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4224.71228787879,
                 "y":633.049225757576
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1431,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":4375.21228787879,
                 "y":633.049225757576
                }, 
                {
                 "gid":74,
                 "height":74,
                 "id":1432,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":80,
                 "x":4558.17228787879,
                 "y":486.257225757576
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":40,
                 "height":90,
                 "id":1379,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"launchBay",
                 "visible":true,
                 "width":150,
                 "x":2221,
                 "y":481.333333333333
                }, 
                {
                 "gid":35,
                 "height":45,
                 "id":1380,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":12
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-200
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":2273.33333333333,
                 "y":481.666666666667
                }, 
                {
                 "height":0,
                 "id":1381,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-37.3333333333333,
                         "y":-98
                        }, 
                        {
                         "x":-156.666666666667,
                         "y":-183.333333333333
                        }, 
                        {
                         "x":-317.333333333333,
                         "y":-182.666666666667
                        }, 
                        {
                         "x":-316.666666666667,
                         "y":-294
                        }, 
                        {
                         "x":-61.3333333333333,
                         "y":-293.333333333333
                        }, 
                        {
                         "x":-61.3333333333333,
                         "y":-216
                        }, 
                        {
                         "x":-92.6666666666667,
                         "y":-183.333333333333
                        }, 
                        {
                         "x":-136.666666666667,
                         "y":-184
                        }],
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"path",
                 "visible":true,
                 "width":0,
                 "x":2297.33333333333,
                 "y":406.333333333333
                }, 
                {
                 "gid":35,
                 "height":45,
                 "id":1382,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":16
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-200
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":2274.66666666667,
                 "y":482.333333333333
                }, 
                {
                 "gid":35,
                 "height":45,
                 "id":1383,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":12
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-200
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":2274.66666666667,
                 "y":481
                }, 
                {
                 "gid":35,
                 "height":45,
                 "id":1384,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":16
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-200
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":2274,
                 "y":481.666666666667
                }, 
                {
                 "gid":24,
                 "height":30,
                 "id":1385,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":1.570796326
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1890.33333333333,
                 "y":386
                }, 
                {
                 "gid":25,
                 "height":30,
                 "id":1386,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1943.66666666667,
                 "y":338
                }, 
                {
                 "gid":21,
                 "height":30,
                 "id":1387,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":3.141592653
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1854.66666666667,
                 "y":93
                }, 
                {
                 "gid":21,
                 "height":30,
                 "id":1388,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":3.141592653
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1953.33333333333,
                 "y":93
                }, 
                {
                 "gid":21,
                 "height":30,
                 "id":1389,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":3.141592653
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2108.66666666667,
                 "y":181.666666666667
                }, 
                {
                 "gid":18,
                 "height":30,
                 "id":1390,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":4.71238898
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1996.33333333333,
                 "y":385.333333333333
                }, 
                {
                 "gid":18,
                 "height":30,
                 "id":1391,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":4.71238898
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":2136,
                 "y":119.666666666667
                }, 
                {
                 "gid":38,
                 "height":28,
                 "id":1392,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"loop"
                        }],
                 "rotation":0,
                 "type":"groundEnemy2",
                 "visible":true,
                 "width":40,
                 "x":2104,
                 "y":393
                }, 
                {
                 "gid":38,
                 "height":28,
                 "id":1393,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"loop"
                        }],
                 "rotation":0,
                 "type":"groundEnemy2",
                 "visible":true,
                 "width":40,
                 "x":2529.33333333333,
                 "y":481.666666666667
                }, 
                {
                 "gid":39,
                 "height":126,
                 "id":1395,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":20
                        }],
                 "rotation":0,
                 "type":"groundEnemy3",
                 "visible":true,
                 "width":120,
                 "x":2556,
                 "y":409.333333333333
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1433,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":16.3333333333333,
                 "y":170.666666666667
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1434,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":81.6666666666667,
                 "y":169.333333333333
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1435,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":145,
                 "y":170
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1436,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":210.333333333333,
                 "y":170
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1437,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":273.666666666667,
                 "y":170.666666666667
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1438,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-250
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":369,
                 "y":362
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1439,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-250
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":402.333333333333,
                 "y":330.666666666667
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1440,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-250
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":435,
                 "y":299.333333333333
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1441,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":4
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":497.666666666667,
                 "y":233.333333333333
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1442,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":4
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":531,
                 "y":266.666666666667
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1443,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":4
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":561.666666666667,
                 "y":298
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1444,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-300
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":16
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":627,
                 "y":425.333333333333
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1445,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":6
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":16
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":775,
                 "y":249
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1446,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":871.666666666667,
                 "y":344.333333333333
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1447,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":8
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-200
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":16
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":967,
                 "y":249
                }, 
                {
                 "gid":34,
                 "height":45,
                 "id":1448,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":9
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-150
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":1097.33333333333,
                 "y":406
                }, 
                {
                 "gid":34,
                 "height":45,
                 "id":1449,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":9
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-150
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":1161.33333333333,
                 "y":470
                }, 
                {
                 "gid":34,
                 "height":45,
                 "id":1450,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":9
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-150
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":1162,
                 "y":342.666666666667
                }, 
                {
                 "gid":34,
                 "height":45,
                 "id":1451,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":9
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }, 
                        {
                         "name":"speed",
                         "type":"int",
                         "value":-150
                        }],
                 "rotation":0,
                 "type":"flyingEnemy3",
                 "visible":true,
                 "width":45,
                 "x":1225.33333333333,
                 "y":406
                }, 
                {
                 "gid":26,
                 "height":50,
                 "id":1452,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1351,
                 "y":183.666666666667
                }, 
                {
                 "height":0,
                 "id":1453,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-352.666666666667,
                         "y":-0.666666666666657
                        }, 
                        {
                         "x":-97.3333333333335,
                         "y":287.333333333333
                        }, 
                        {
                         "x":-191.333333333333,
                         "y":64.6666666666667
                        }, 
                        {
                         "x":-320,
                         "y":64
                        }, 
                        {
                         "x":-132.666666666667,
                         "y":286
                        }, 
                        {
                         "x":12.6666666666665,
                         "y":286.666666666667
                        }, 
                        {
                         "x":-93.3333333333335,
                         "y":114
                        }, 
                        {
                         "x":-134,
                         "y":114
                        }],
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }],
                 "rotation":0,
                 "type":"path",
                 "visible":true,
                 "width":0,
                 "x":1376,
                 "y":159.333333333333
                }, 
                {
                 "gid":26,
                 "height":50,
                 "id":1454,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1415.66666666667,
                 "y":184.333333333333
                }, 
                {
                 "gid":26,
                 "height":50,
                 "id":1455,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1478.33333333333,
                 "y":183
                }, 
                {
                 "gid":26,
                 "height":50,
                 "id":1456,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1543,
                 "y":185
                }, 
                {
                 "gid":26,
                 "height":50,
                 "id":1457,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"points"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1606.33333333333,
                 "y":184.333333333333
                }, 
                {
                 "gid":20,
                 "height":30,
                 "id":1458,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":0.785398163
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1645,
                 "y":483
                }, 
                {
                 "gid":20,
                 "height":30,
                 "id":1459,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"rotation",
                         "type":"float",
                         "value":0.785398163
                        }],
                 "rotation":0,
                 "type":"groundEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1825,
                 "y":484
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":9,
 "nextobjectid":1460,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/mapAssets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":700
});