(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelThreeWIP",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[
                {
                 "height":64,
                 "id":1252,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":-0.166667
                }, 
                {
                 "height":32,
                 "id":1253,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":575.833
                }, 
                {
                 "height":64,
                 "id":1254,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":-0.166667
                }, 
                {
                 "height":32,
                 "id":1255,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":-0.5,
                 "y":575.833
                }],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":66,
                 "height":150,
                 "id":1328,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-869.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1329,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-720.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1330,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-570.916666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1331,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-420.416666666667,
                 "y":631.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1332,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-270.916666666667,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1333,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-121.416666666667,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1334,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":28.5833333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1335,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":178.583333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1336,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":329.083333333333,
                 "y":632.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1337,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-869.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1338,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-719.416666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1339,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-569.416666666667,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1340,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-418.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1341,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-268.916666666667,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1342,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":-118.916666666667,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1343,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":31.5833333333333,
                 "y":66.25
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1344,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":181.083333333333,
                 "y":65.75
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1345,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":330.583333333333,
                 "y":65.75
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1346,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":328,
                 "y":485.333333333333
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1347,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":368,
                 "y":485.333333333333
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1348,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":406.666666666667,
                 "y":485.333333333333
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1349,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":445.333333333333,
                 "y":485.333333333333
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1350,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":481.081833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1351,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":631.584833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1352,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":781.584833333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1353,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":932.084833333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1354,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1082.08483333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1355,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1232.08483333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1356,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1382.58483333333,
                 "y":65.9166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1357,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1532.08513333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1358,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1681.58483333333,
                 "y":65.4166666666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1359,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":478.706833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1360,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":627.709833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1361,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":777.709833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1362,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":928.209833333333,
                 "y":631.625166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1363,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1077.70983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1364,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1227.20983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1365,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1377.20983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1366,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1527.21013333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":66,
                 "height":150,
                 "id":1367,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3AncientBoard",
                 "visible":true,
                 "width":150,
                 "x":1677.70983333333,
                 "y":632.125166666667
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1368,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":1676.62683333333,
                 "y":485.208166666667
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1369,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":1716.62683333333,
                 "y":485.208166666667
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1370,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":1755.29383333333,
                 "y":485.208166666667
                }, 
                {
                 "gid":70,
                 "height":40,
                 "id":1371,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"lvl3Square2",
                 "visible":true,
                 "width":40,
                 "x":1793.95983333333,
                 "y":485.208166666667
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":9,
 "nextobjectid":1372,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/mapAssets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":700
});