(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOneWIP",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[
                {
                 "height":64,
                 "id":1346,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":1,
                 "id":1348,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1,
                 "x":57,
                 "y":247
                }, 
                {
                 "height":32,
                 "id":1349,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22560,
                 "x":0,
                 "y":576
                }],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":9,
                 "height":21,
                 "id":1252,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1306,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":208,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1307,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":256,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1308,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":304,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1309,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":352,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1310,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"1"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":400,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1311,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":592,
                 "y":88
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1312,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":656,
                 "y":88
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1313,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":720,
                 "y":88
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1314,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":784,
                 "y":88
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1315,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"string",
                         "value":"2"
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":848,
                 "y":88
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1317,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1056,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1318,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1096,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1319,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1136,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1320,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1176,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1321,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1216,
                 "y":376
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":1322,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":1256,
                 "y":376
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1327,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1424,
                 "y":512
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1328,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1552,
                 "y":360
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1329,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1696,
                 "y":208
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":1330,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-150
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":1840,
                 "y":56
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1331,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":504
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1332,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":200,
                 "y":504
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1334,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":240,
                 "y":504
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1335,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":536
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1336,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":568
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1337,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":64
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1338,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":96
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1339,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":160,
                 "y":600
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1340,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":32
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1341,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":64
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1342,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":96
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1343,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":608
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1344,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":576
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":1345,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"Speed",
                         "type":"int",
                         "value":-100
                        }, 
                        {
                         "name":"difficulty",
                         "type":"int",
                         "value":1
                        }, 
                        {
                         "name":"pattern",
                         "type":"string",
                         "value":"none"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":480,
                 "y":544
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":9,
         "name":"Foreground",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":14,
 "nextobjectid":1350,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/mapAssets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":700
});