(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOne",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":9,
                 "height":21,
                 "id":683,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":193,
                 "y":120.666666666667
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":684,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":226.333333333333,
                 "y":122
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":685,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":261,
                 "y":122
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":686,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":293,
                 "y":122
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":687,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":389,
                 "y":311.333333333333
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":688,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":427.666666666667,
                 "y":312.666666666667
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":689,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":465,
                 "y":312.666666666667
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":690,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":581.666666666667,
                 "y":523.666666666667
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":691,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":635,
                 "y":522.333333333333
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":692,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":3
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":695,
                 "y":522.333333333333
                }, 
                {
                 "gid":9,
                 "height":21,
                 "id":694,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1",
                 "visible":true,
                 "width":30,
                 "x":378.333333333333,
                 "y":218
                }, 
                {
                 "gid":14,
                 "height":50,
                 "id":695,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"PathType",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2sine",
                 "visible":true,
                 "width":50,
                 "x":501.666666666667,
                 "y":426.333333333333
                }, 
                {
                 "gid":12,
                 "height":21,
                 "id":696,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"PathType",
                         "type":"string",
                         "value":"sine"
                        }],
                 "rotation":0,
                 "type":"flyingEnemy1sine",
                 "visible":true,
                 "width":30,
                 "x":839.666666666667,
                 "y":390
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":697,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":535,
                 "y":110.333333333333
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":698,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":203,
                 "y":302.333333333333
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":8,
 "nextobjectid":699,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":400
});