(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOne",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                {
                 "gid":10,
                 "height":50,
                 "id":802,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":25,
                 "y":389
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":803,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":81,
                 "y":391
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":804,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":135,
                 "y":389
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":805,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":193,
                 "y":389
                }, 
                {
                 "height":0,
                 "id":808,
                 "name":"",
                 "polygon":[
                        {
                         "x":34,
                         "y":-57
                        }, 
                        {
                         "x":-91,
                         "y":22.5
                        }, 
                        {
                         "x":-118,
                         "y":250
                        }, 
                        {
                         "x":83,
                         "y":162
                        }],
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"path",
                 "visible":true,
                 "width":0,
                 "x":168,
                 "y":117
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":810,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":370,
                 "y":184
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":811,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":426,
                 "y":184
                }, 
                {
                 "gid":10,
                 "height":50,
                 "id":812,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"flyingEnemy2",
                 "visible":true,
                 "width":50,
                 "x":488,
                 "y":186
                }, 
                {
                 "height":0,
                 "id":813,
                 "name":"",
                 "polygon":[
                        {
                         "x":-36,
                         "y":334
                        }, 
                        {
                         "x":-40,
                         "y":75
                        }, 
                        {
                         "x":199,
                         "y":147
                        }, 
                        {
                         "x":202.6147228568,
                         "y":331.890518152384
                        }, 
                        {
                         "x":138.280330665498,
                         "y":432.235639983761
                        }, 
                        {
                         "x":8.22162162162158,
                         "y":438.52972972973
                        }],
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":2
                        }],
                 "rotation":0,
                 "type":"path",
                 "visible":true,
                 "width":0,
                 "x":429,
                 "y":84
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":8,
 "nextobjectid":814,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":400
});