(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("warpZoneWIP",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[],
         "opacity":1,
         "properties":[
                {
                 "name":"clearColor",
                 "type":"color",
                 "value":"#ff000053"
                }],
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":43,
                 "height":74,
                 "id":1250,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":433.667,
                 "y":97
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1251,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":929.667,
                 "y":581
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1252,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":1224.33,
                 "y":462.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1253,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":1507,
                 "y":325
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1254,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":1787,
                 "y":145
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1255,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":2100.33,
                 "y":489
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1256,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":2444.33,
                 "y":75.6667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1257,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":2832.33,
                 "y":329
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1258,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":3207,
                 "y":605
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1259,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":3201.67,
                 "y":183.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1260,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":3548.33,
                 "y":83.6667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1261,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":3833.67,
                 "y":441
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1262,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":4236.33,
                 "y":329
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1263,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":4509.67,
                 "y":187.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1264,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":4508.33,
                 "y":490.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1265,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":4800.33,
                 "y":606.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1266,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":4795,
                 "y":433
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1267,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":5205.67,
                 "y":77
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1268,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":5425.67,
                 "y":250.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1269,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":5615,
                 "y":489
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1270,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6049.67,
                 "y":607.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1271,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6053.67,
                 "y":75.6667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1272,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6367,
                 "y":167.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1273,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6385.67,
                 "y":511.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1274,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6689.67,
                 "y":246.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1275,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":6685.67,
                 "y":398.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1276,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":7020.33,
                 "y":327.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1277,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":7203,
                 "y":75.6667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1278,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":7240.33,
                 "y":606.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1279,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":7661.67,
                 "y":438.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1280,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":7961.67,
                 "y":177
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1281,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":8211,
                 "y":603.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1282,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":8519,
                 "y":259.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1283,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":9139,
                 "y":255.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1284,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":9321.67,
                 "y":419.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1285,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":9741.67,
                 "y":594.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1286,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":9975,
                 "y":78.3333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1287,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10363,
                 "y":206.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1288,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10365.7,
                 "y":378
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1289,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10364.3,
                 "y":523.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1290,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10652.3,
                 "y":607.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1291,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10656.3,
                 "y":123.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1292,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":10973.7,
                 "y":278.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1293,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":11305.7,
                 "y":477
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1294,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":11709.7,
                 "y":602.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1295,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":11916.3,
                 "y":511.667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1296,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":12087,
                 "y":413
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1297,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":12396.3,
                 "y":79.6667
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1298,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":12863,
                 "y":338.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1299,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13177.7,
                 "y":121
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1300,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13428.3,
                 "y":490.333
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1363,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13647,
                 "y":96
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1364,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13827,
                 "y":257
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1365,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13966,
                 "y":403
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1366,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":13796,
                 "y":540
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1367,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14221,
                 "y":598
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1368,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14421,
                 "y":405
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1369,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14278,
                 "y":260
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1370,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14461,
                 "y":89
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1371,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14787,
                 "y":124
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1372,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15052,
                 "y":185
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1373,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15312,
                 "y":248
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1374,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15551,
                 "y":318
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1375,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15798,
                 "y":391
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1376,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16022,
                 "y":477
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1377,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16244,
                 "y":571
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1378,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14749,
                 "y":265
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1379,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":14730,
                 "y":499
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1380,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15069,
                 "y":595
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1381,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15443,
                 "y":484
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1382,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15508,
                 "y":108
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1383,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16007,
                 "y":181
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1384,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":15795,
                 "y":583
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1385,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16383,
                 "y":323
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1386,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16673,
                 "y":120
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1387,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16866,
                 "y":290
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1388,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":16633,
                 "y":488
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1389,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17091,
                 "y":553
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1390,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17271,
                 "y":358
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1391,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17142,
                 "y":88
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1392,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17484,
                 "y":613
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1393,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17615,
                 "y":542
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1394,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":17757,
                 "y":473
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1396,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":18030,
                 "y":348
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1397,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":18178,
                 "y":267
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1398,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":18302,
                 "y":185
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1399,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":18662,
                 "y":94
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1400,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":18659,
                 "y":246
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1401,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19056,
                 "y":158
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1402,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19262,
                 "y":81
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1403,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19056,
                 "y":323
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1404,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19358,
                 "y":220
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1405,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19650,
                 "y":313
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1406,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19513,
                 "y":454
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1407,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19719,
                 "y":587
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1408,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":19936,
                 "y":198
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1409,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20096,
                 "y":340
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1410,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20324,
                 "y":429
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1411,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20581,
                 "y":567
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1412,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20453,
                 "y":156
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1413,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20884,
                 "y":82
                }, 
                {
                 "gid":43,
                 "height":74,
                 "id":1414,
                 "name":"",
                 "properties":[
                        {
                         "name":"Group",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"warpObstacle",
                 "visible":true,
                 "width":107,
                 "x":20895,
                 "y":324
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":9,
 "nextobjectid":1423,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/raw assets\/mapAssets\/objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":700
});