
var exampleExplosion = {
    "speed":400,
    "size":5,
    "angle":0,
    "emissionRate":250,
    "duration":0.1,
    "immortal":false,
    "particleLife":0.5,
    "color":[38,
    208,
    46,
    1],
    "endColor":[38,
    208,
    46,
    0.1],
    "useTexture":false,
    "textureAdditive":false,
    "fadeAlpha":true,
    "fadeSpeed":true,
    "fadeSize":true,
    "gravity":0,
    "xVar":25,
    "yVar":25,
    "speedVar":150,
    "sizeVar":2,
    "angleVar":360,
    "particleLifeVar":0,
    }

var getCapsule = {"speed":55.6,"size":1.2,"angle":333,"emissionRate":1927.9,"duration":0.1,"immortal":false,"particleLife":0.9,"color":[255,255,255,1],"endColor":[118,224,1,1],"useGradient":false,"useTexture":false,"textureAdditive":false,"fadeAlpha":true,"fadeSpeed":true,"fadeSize":true,"gravity":0,"xVar":0,"yVar":0,"speedVar":150,"sizeVar":1,"angleVar":360,"particleLifeVar":0,"startColorVar":[0,0,0,0],"endColorVar":[0,0,0,0],"endColorToggle":true,"colorVarToggle":false}