(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelOne",
{ "height":19,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":2,
         "name":"Terrain",
         "objects":[
                {
                 "gid":1,
                 "height":73,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":427,
                 "y":526
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":553,
                 "y":178
                }, 
                {
                 "gid":1,
                 "height":73,
                 "id":20,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":741,
                 "y":454
                }, 
                {
                 "gid":7,
                 "height":90,
                 "id":24,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":90,
                 "x":865,
                 "y":233
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Enemies",
         "objects":[
                ],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":6,
 "nextobjectid":39,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"objects.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":400
});